### ISSUE TITLE
+[TapSenseAds getSDKVersion] returns previous version

### ISSUE THREAD

**Issue by justadreamer** [TapSense/tapsense-ads-ios-sdk#1]
I've downloaded your SDK v.3.2.1, but a call to the mentioned method returns '2.3.1'.  Please fix.

**Comment by crystalt** [comment]
Thanks for downloading our SDK! 

Tried to reproduce the issue:
- Tested with[TapSense Base SDK.zip] (https://s3.amazonaws.com/ts-sdks/ios-pub/tapsense_ios_publisher_sdk_3.2.1_base.zip)
- Tested with [TapSense Full SDK.zip] (https://s3.amazonaws.com/ts-sdks/ios-pub/tapsense_ios_publisher_sdk_3.2.1_full.zip)
- Tested using CocoaPods integration

In all cases, `[TapSenseAds getSDKVersion]` returned 3.2.1. 

Please try re-downloading the SDK, and feel free to email us at pub@tapsense.com if you have any specific questions. Thanks!
